# Generated by Django 4.0.3 on 2022-03-21 09:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saveEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(max_length=50)),
                ('my_email', models.CharField(max_length=50)),
                ('my_mno', models.CharField(max_length=15)),
                ('my_websitename', models.CharField(max_length=50)),
                ('my_message', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='my_name', unique=True)),
            ],
        ),
    ]
