# Generated by Django 4.0.3 on 2022-03-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactenquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveenquiry',
            name='my_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
